APP:
  PROJECT_NAME: Your Project Name
  PROJECT_VERSION: 1.0.0
  ENVIRONMENT: !ENV ${ENVIRONMENT}
  DEBUG: False
  TESTING: False

DATABASE:
  BASE_URL: !ENV ${DATABASE_URL} # PostgreSQL database

SECURITY:
  JWT_EXPIRE_MINUTES: !ENV ${JWT_EXPIRE_MINUTES} # It is recommended to be shorter than 5 minutes
  JWT_ALGORITHM: !ENV ${JWT_ALGORITHM}
  JWT_SECRET_KEY: !ENV ${JWT_SECRET_KEY} # To generate a secure random secret key use the command: openssl rand -hex 512

TESTING:
  USER_EMAIL: !ENV ${USER_EMAIL}
  USER_PASSWORD: !ENV ${USER_PASSWORD}
  USER_STATUS: !ENV ${USER_STATUS}
