name: On Push

on: [push]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DATABASE_URI: ${{ secrets.DATABASE_URI }}

jobs:
  build-app-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  quality-lint-workflow:
    if: success()
    runs-on: ubuntu-latest
    needs: build-app-workflow
    steps:
      - name: Lint with pylint
        run: |
          pip install pylint
          pylint --recursive=y .

  quality-flake8-workflow:
    if: success()
    runs-on: ubuntu-latest
    needs: quality-lint-workflow
    steps:
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

  # test-unittest-workflow:
  #   if: success()
  #   runs-on: ubuntu-latest
  #   needs: quality-flake8-workflow
  #   steps:
  #     - name: Unit test
  #       run: |
  #         pip install pytest
  #         pytest tests/unit_tests/*

  # test-apitest-workflow:
  #   if: success()
  #   runs-on: ubuntu-latest
  #   needs: test-unittest-workflow
  #   steps:
  #     - name: API test
  #       run: |
  #         pip install pytest
  #         pytest tests/api_tests/*
